from pathlib import Path

BASE_DIR = Path(r"E:\LUMINOUS JOURNEY")

DATABASE_DIR = BASE_DIR / "01_DATABASE"
PROMPT_DIR = BASE_DIR / "02_MASTER_PROMPT"
TEMPLATE_DIR = BASE_DIR / "03_TEMPLATE"
JSON_DIR = BASE_DIR / "04_JSON"
OUTPUT_DIR = BASE_DIR / "05_OUTPUT"
IMAGE_PROMPT_DIR = BASE_DIR / "06_IMAGE_PROMPT"
VIDEO_PROMPT_DIR = BASE_DIR / "07_VIDEO_PROMPT"
SEO_DIR = BASE_DIR / "08_SEO"
TTS_DIR = BASE_DIR / "09_TTS"
ARCHIVE_DIR = BASE_DIR / "10_ARCHIVE"
SCRIPT_DIR = BASE_DIR / "11_SCRIPT"
APP_DIR = BASE_DIR / "12_APP"
LOG_DIR = BASE_DIR / "13_LOG"
PROMPT_DIR = BASE_DIR / "02_MASTER_PROMPT"

PROMPT_FILE = PROMPT_DIR / "LUMINOUS JOURNEY DAILY PRODUCTION MASTER PROMPT v5LZ.docx"

JSON_DIR = BASE_DIR / "04_JSON"

OUTPUT_DIR = BASE_DIR / "05_OUTPUT"
print("Configuration Loaded Successfully")
LANGUAGES = [
    "IND",
    "ENG",
    "ESP",
    "ZHT",
    "ZHS",
    "PINYIN"
]