from providers.base import AIProvider


class MockProvider(AIProvider):

    name = "mock"

    MOCK_RESPONSE = """# TITLE

Mock Title

# SCRIPT

This is a mock script generated by MockProvider.

# SEO

Mock SEO Description

# HASHTAGS

#mock #luminousjourney

# IMAGE_PROMPTS

A cinematic sunrise over mountains with warm golden light.

# METADATA

AUTHOR=Mock
VERSION=0.5.0
"""

    def generate(
        self,
        prompt: str,
        max_tokens: int = 512,
    ) -> str:

        return self.MOCK_RESPONSE

    def stream(
        self,
        prompt: str,
        max_tokens: int = 512,
    ):

        yield self.MOCK_RESPONSE

    @property
    def model(
        self,
    ) -> str:

        return "mock"

    def __repr__(
        self,
    ) -> str:

        return (

            f"{self.__class__.__name__}"

            f"(name='{self.name}')"

        )