class MockProvider:

    name = "Mock"

    def generate(
        self,
        prompt,
        max_tokens=1000,
    ):

        return f"""
MOCK RESPONSE

Prompt Length : {len(prompt)}

Lorem ipsum dolor sit amet.

Generated by MockProvider.
"""